##################################################

resolver: lts-12.7

packages:
  - "."

##################################################



##################################################

nix:
  enable:   true
  packages: [ gmp libcxx zlib ]
  #icu

##################################################